export const categories = [
  'ALL',
  'PATRIOTIC',
  'COMMUNITY',
  'FICTION',
  'DRAMA',
  'NEWS',
  'SONGS',
  'EPIC MYTH',
  'SIGN-OFF',
]

export const shows = [
  {
    id: 'malgudi-days',
    title: 'Malgudi Days',
    titleHi: 'मालगुडी डेज़',
    year: '1986–1987',
    category: 'FICTION',
    description: 'Adapted from R.K. Narayan\'s stories. A quiet fictional town in South India where every day brought a new gentle adventure.',
    image: '/images/doordarshan/malgudi-days.png',
    gradient: 'linear-gradient(135deg, #8B6914 0%, #2E4A1E 100%)',
  },
  {
    id: 'shaktimaan',
    title: 'Shaktimaan',
    titleHi: 'शक्तिमान',
    year: '1997–2005',
    category: 'FICTION',
    description: 'India\'s first superhero. Every Sunday morning, the entire colony gathered around one TV set.',
    image: '/images/doordarshan/shaktimaan.png',
    gradient: 'linear-gradient(135deg, #8B1A1A 0%, #1A1A4B 100%)',
  },
  {
    id: 'buniyaad',
    title: 'Buniyaad',
    titleHi: 'बुनियाद',
    year: '1986–1987',
    category: 'DRAMA',
    description: 'The saga of two families across the Partition. Evenings fell silent when this came on.',
    image: '/images/doordarshan/buniyaad.png',
    gradient: 'linear-gradient(135deg, #5A3925 0%, #1A1A2E 100%)',
  },
  {
    id: 'chandrakanta',
    title: 'Chandrakanta',
    titleHi: 'चंद्रकांता',
    year: '1994–1996',
    category: 'FICTION',
    description: 'Tilism and aiyaari — a fantasy world of secret tunnels, magic, and love between two royal houses.',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #6B2F8A 0%, #1A2E4A 100%)',
  },
  {
    id: 'mahabharat',
    title: 'Mahabharat',
    titleHi: 'महाभारत',
    year: '1988–1990',
    category: 'EPIC MYTH',
    description: 'B.R. Chopra\'s epic retelling. Streets emptied on Sunday mornings. The country stopped to watch.',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #C98A48 0%, #5A2E14 100%)',
  },
  {
    id: 'byomkesh-bakshi',
    title: 'Byomkesh Bakshi',
    titleHi: 'ब्योमकेश बक्शी',
    year: '1993–1997',
    category: 'DRAMA',
    description: 'The truth-seeker of Calcutta. Rajit Kapur brought Sharadindu\'s detective to life in black and white Kolkata.',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #2E2E2E 0%, #5A4A32 100%)',
  },
  {
    id: 'ramayan',
    title: 'Ramayan',
    titleHi: 'रामायण',
    year: '1987–1988',
    category: 'EPIC MYTH',
    description: 'Ramanand Sagar\'s retelling. 78 episodes that united the entire nation every Sunday morning.',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #D4773A 0%, #8B4513 100%)',
  },
  {
    id: 'hum-log',
    title: 'Hum Log',
    titleHi: 'हम लोग',
    year: '1984–1985',
    category: 'DRAMA',
    description: 'India\'s first soap opera. The Basant Ram family and their everyday struggles felt like our own.',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #6B5B3E 0%, #2E1A0A 100%)',
  },
  {
    id: 'chitrahar',
    title: 'Chitrahar',
    titleHi: 'चित्रहार',
    year: '1982–1998',
    category: 'SONGS',
    description: 'Wednesday and Friday evenings belonged to film songs. The only way to watch music videos before cable.',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #C66A32 0%, #4A1A3E 100%)',
  },
  {
    id: 'rangoli',
    title: 'Rangoli',
    titleHi: 'रंगोली',
    year: '1972–1998',
    category: 'SONGS',
    description: 'Sunday morning film songs. The opening title card with the rangoli patterns — unforgettable.',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #D4773A 0%, #6B2F4A 100%)',
  },
  {
    id: 'surabhi',
    title: 'Surabhi',
    titleHi: 'सुरभि',
    year: '1993–2001',
    category: 'COMMUNITY',
    description: 'Siddharth Kak and Renuka Shahane exploring India\'s art, culture and heritage. "Jawaab dijiye, Surabhi ke sandooq mein."',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #2E6B4A 0%, #1A2E1A 100%)',
  },
  {
    id: 'krishi-darshan',
    title: 'Krishi Darshan',
    titleHi: 'कृषि दर्शन',
    year: '1967–present',
    category: 'COMMUNITY',
    description: 'The longest-running show on Indian television. For the farmers, by the farmers.',
    image: '/images/doordarshan/default-poster.png',
    gradient: 'linear-gradient(135deg, #4A6B2E 0%, #2E4A1E 100%)',
  },
]

export const schedule = [
  { time: '06:00 AM', show: 'Vandé Mataram & National Broadcast Opening Tunes', price: '' },
  { time: '06:30 AM', show: 'Krishi Darshan: Monsoon in Bundelkhand, presented', price: '' },
  { time: '07:15 AM', show: 'Subah Savere — Yoga & exercise with Baba Ramdev', price: '' },
  { time: '08:00 AM', show: 'Rangoli — film songs to start your Sunday', price: '' },
  { time: '09:30 AM', show: 'Ramayan — Lanka Kand, Part IV of XVI', price: '' },
  { time: '10:30 AM', show: 'Mahabharat — Bhishma Pratigya', price: '' },
  { time: '12:00 PM', show: 'Samachar — National News, read by Salma Sultan', price: '' },
  { time: '12:30 PM', show: 'Krishi — Hindi-language agriculture & farming updates', price: '' },
  { time: '01:00 PM', show: 'Regional — Malgudi Ki Kahaniyan (Hindi Dub)', price: 'FREE' },
  { time: '02:30 PM', show: 'I.N.D. Ltd: 118 Cricket Ind. score & 18 day odi analysis', price: 'PAID' },
  { time: '04:00 PM', show: 'Shaktimaan — "Kilvisho ne puri dilli ko qaid kiya"', price: '' },
  { time: '05:00 PM', show: 'Chitrahar — Wednesday special', price: '' },
  { time: '06:00 PM', show: 'Samachar — Evening bulletin in Hindi & English', price: '' },
  { time: '07:30 PM', show: 'Buniyaad — Part 34, "The letter from Lahore"', price: '' },
  { time: '08:30 PM', show: 'Byomkesh Bakshi — "Adrishya Trikon"', price: 'FREE' },
  { time: '10:00 PM', show: 'Surabhi — Exploring the temples of Hampi', price: '' },
  { time: '11:00 PM', show: 'Late Night — National Anthem & Sign-Off Tunes', price: 'PAID NFT' },
]
