export const hotspots = [
  {
    id: 'bhajans',
    label: 'Bhajans',
    icon: '🪔',
    description: 'Morning prayers, devotional songs and aarti.',
    route: '/bhajans',
    // Position as % of image dimensions
    x: 8,
    y: 32,
    hoverSound: 'bell',
  },
  {
    id: 'photo-wall',
    label: 'Photo Wall',
    icon: '🖼️',
    description: 'Old photographs. Frozen moments from the past.',
    route: '/album',
    x: 28,
    y: 18,
    hoverSound: 'paper',
  },
  {
    id: 'doordarshan',
    label: 'Doordarshan',
    icon: '📺',
    description: 'Relive the shows that brought everyone together.',
    route: '/doordarshan',
    x: 86,
    y: 62,
    hoverSound: 'tv',
  },
  {
    id: 'radio',
    label: 'Radio Corner',
    icon: '📻',
    description: 'Turn the dial. Hear the crackle of shortwave.',
    route: '/radio',
    x: 12,
    y: 62,
    hoverSound: 'radio',
  },
  {
    id: 'drawer',
    label: 'The Drawer',
    icon: '📦',
    description: 'Cassettes, comics, books and little treasures.',
    route: '/drawer',
    x: 38,
    y: 72,
    hoverSound: 'cassette',
  },
  {
    id: 'courtyard',
    label: 'Courtyard',
    icon: '🚪',
    description: 'Games we played for hours with our friends.',
    route: '/album',
    x: 52,
    y: 45,
    hoverSound: 'door',
  },
  {
    id: 'letters',
    label: 'Letters Desk',
    icon: '✉️',
    description: 'Read memories from others. Write your own inland letter.',
    route: '/letters',
    x: 50,
    y: 82,
    hoverSound: 'paper',
  },
]
